-- AUTO-GENERATED by scripts/generate-rank-data.mjs — do not edit by hand.
-- Source: Tank-Me-Later Vercel API (falls back to Raider.io if unavailable).

TankMeLater = TankMeLater or {}
TankMeLater.Data = {}

-- Season metadata
TankMeLater.Data.Season      = "season-mn-1"
TankMeLater.Data.UpdatedDate = "2026-08-23"

-- Pre-computed minimum score for each rank boundary.
-- Ordered highest rank first (Challenger index 1, Iron IV last).
-- scoreToRank() scans this table and returns the first entry where score >= minScore.
TankMeLater.Data.Cutoffs = {
    { tier = "Challenger" , division = nil  , label = "Challenger"     , minScore = 4233, topPercent =   0.02 },
    { tier = "Grandmaster", division = nil  , label = "Grandmaster"    , minScore = 4222, topPercent =   0.06 },
    { tier = "Master"     , division = nil  , label = "Master"         , minScore = 4041, topPercent =   0.71 },
    { tier = "Diamond"    , division = "I"  , label = "Diamond I"      , minScore = 3946, topPercent =   1.23 },
    { tier = "Diamond"    , division = "II" , label = "Diamond II"     , minScore = 3889, topPercent =   2.15 },
    { tier = "Diamond"    , division = "III", label = "Diamond III"    , minScore = 3857, topPercent =   2.67 },
    { tier = "Diamond"    , division = "IV" , label = "Diamond IV"     , minScore = 3767, topPercent =   4.12 },
    { tier = "Emerald"    , division = "I"  , label = "Emerald I"      , minScore = 3599, topPercent =   6.81 },
    { tier = "Emerald"    , division = "II" , label = "Emerald II"     , minScore = 3490, topPercent =   8.57 },
    { tier = "Emerald"    , division = "III", label = "Emerald III"    , minScore = 3373, topPercent =  11.14 },
    { tier = "Emerald"    , division = "IV" , label = "Emerald IV"     , minScore = 3248, topPercent =  16.12 },
    { tier = "Platinum"   , division = "I"  , label = "Platinum I"     , minScore = 3189, topPercent =   18.5 },
    { tier = "Platinum"   , division = "II" , label = "Platinum II"    , minScore = 3101, topPercent =  22.01 },
    { tier = "Platinum"   , division = "III", label = "Platinum III"   , minScore = 2997, topPercent =  26.46 },
    { tier = "Platinum"   , division = "IV" , label = "Platinum IV"    , minScore = 2850, topPercent =   33.8 },
    { tier = "Gold"       , division = "I"  , label = "Gold I"         , minScore = 2775, topPercent =  37.53 },
    { tier = "Gold"       , division = "II" , label = "Gold II"        , minScore = 2668, topPercent =  42.91 },
    { tier = "Gold"       , division = "III", label = "Gold III"       , minScore = 2545, topPercent =  49.01 },
    { tier = "Gold"       , division = "IV" , label = "Gold IV"        , minScore = 2372, topPercent =  57.69 },
    { tier = "Silver"     , division = "I"  , label = "Silver I"       , minScore = 2285, topPercent =  62.03 },
    { tier = "Silver"     , division = "II" , label = "Silver II"      , minScore = 2175, topPercent =  67.51 },
    { tier = "Silver"     , division = "III", label = "Silver III"     , minScore = 2066, topPercent =  72.98 },
    { tier = "Silver"     , division = "IV" , label = "Silver IV"      , minScore = 1937, topPercent =   79.4 },
    { tier = "Bronze"     , division = "I"  , label = "Bronze I"       , minScore = 1862, topPercent =  83.13 },
    { tier = "Bronze"     , division = "II" , label = "Bronze II"      , minScore = 1780, topPercent =  87.26 },
    { tier = "Bronze"     , division = "III", label = "Bronze III"     , minScore = 1699, topPercent =   91.3 },
    { tier = "Bronze"     , division = "IV" , label = "Bronze IV"      , minScore = 1601, topPercent =  96.16 },
    { tier = "Iron"       , division = "I"  , label = "Iron I"         , minScore = 1564, topPercent =  98.03 },
    { tier = "Iron"       , division = "II" , label = "Iron II"        , minScore = 1543, topPercent =  99.06 },
    { tier = "Iron"       , division = "III", label = "Iron III"       , minScore = 1535, topPercent =  99.48 },
    { tier = "Iron"       , division = "IV" , label = "Iron IV"        , minScore = 1525, topPercent =    100 },
}

-- Tier colors as (r, g, b) in [0-1] range, matching the Tank-Me-Later web app.
TankMeLater.Data.TierColors = {
    Challenger  = { r = 0.957, g = 0.816, b = 0.247 },
    Grandmaster = { r = 0.910, g = 0.145, b = 0.231 },
    Master      = { r = 0.608, g = 0.349, b = 0.714 },
    Diamond     = { r = 0.310, g = 0.765, b = 0.969 },
    Emerald     = { r = 0.180, g = 0.800, b = 0.443 },
    Platinum    = { r = 0.102, g = 0.737, b = 0.612 },
    Gold        = { r = 0.953, g = 0.612, b = 0.071 },
    Silver      = { r = 0.584, g = 0.647, b = 0.651 },
    Bronze      = { r = 0.804, g = 0.498, b = 0.196 },
    Iron        = { r = 0.498, g = 0.549, b = 0.553 },
}
