-- AUTO-GENERATED by scripts/generate-rank-data.mjs — do not edit by hand.
-- Source: Tank-Me-Later Vercel API (falls back to Raider.io if unavailable).

TankMeLater = TankMeLater or {}
TankMeLater.Data = {}

-- Season metadata
TankMeLater.Data.Season      = "season-mn-1"
TankMeLater.Data.UpdatedDate = "2026-08-09"

-- Pre-computed minimum score for each rank boundary.
-- Ordered highest rank first (Challenger index 1, Iron IV last).
-- scoreToRank() scans this table and returns the first entry where score >= minScore.
TankMeLater.Data.Cutoffs = {
    { tier = "Challenger" , division = nil  , label = "Challenger"     , minScore = 4224, topPercent =   0.02 },
    { tier = "Grandmaster", division = nil  , label = "Grandmaster"    , minScore = 4209, topPercent =   0.07 },
    { tier = "Master"     , division = nil  , label = "Master"         , minScore = 4017, topPercent =   0.73 },
    { tier = "Diamond"    , division = "I"  , label = "Diamond I"      , minScore = 3922, topPercent =   1.26 },
    { tier = "Diamond"    , division = "II" , label = "Diamond II"     , minScore = 3865, topPercent =   2.21 },
    { tier = "Diamond"    , division = "III", label = "Diamond III"    , minScore = 3834, topPercent =   2.74 },
    { tier = "Diamond"    , division = "IV" , label = "Diamond IV"     , minScore = 3745, topPercent =   4.23 },
    { tier = "Emerald"    , division = "I"  , label = "Emerald I"      , minScore = 3592, topPercent =   6.78 },
    { tier = "Emerald"    , division = "II" , label = "Emerald II"     , minScore = 3484, topPercent =   8.59 },
    { tier = "Emerald"    , division = "III", label = "Emerald III"    , minScore = 3371, topPercent =  11.14 },
    { tier = "Emerald"    , division = "IV" , label = "Emerald IV"     , minScore = 3249, topPercent =  16.03 },
    { tier = "Platinum"   , division = "I"  , label = "Platinum I"     , minScore = 3191, topPercent =  18.36 },
    { tier = "Platinum"   , division = "II" , label = "Platinum II"    , minScore = 3104, topPercent =  21.87 },
    { tier = "Platinum"   , division = "III", label = "Platinum III"   , minScore = 3000, topPercent =  26.32 },
    { tier = "Platinum"   , division = "IV" , label = "Platinum IV"    , minScore = 2853, topPercent =  33.63 },
    { tier = "Gold"       , division = "I"  , label = "Gold I"         , minScore = 2779, topPercent =  37.35 },
    { tier = "Gold"       , division = "II" , label = "Gold II"        , minScore = 2670, topPercent =  42.77 },
    { tier = "Gold"       , division = "III", label = "Gold III"       , minScore = 2547, topPercent =  48.92 },
    { tier = "Gold"       , division = "IV" , label = "Gold IV"        , minScore = 2371, topPercent =  57.73 },
    { tier = "Silver"     , division = "I"  , label = "Silver I"       , minScore = 2282, topPercent =  62.18 },
    { tier = "Silver"     , division = "II" , label = "Silver II"      , minScore = 2171, topPercent =  67.71 },
    { tier = "Silver"     , division = "III", label = "Silver III"     , minScore = 2060, topPercent =  73.23 },
    { tier = "Silver"     , division = "IV" , label = "Silver IV"      , minScore = 1933, topPercent =   79.6 },
    { tier = "Bronze"     , division = "I"  , label = "Bronze I"       , minScore = 1858, topPercent =  83.32 },
    { tier = "Bronze"     , division = "II" , label = "Bronze II"      , minScore = 1775, topPercent =  87.46 },
    { tier = "Bronze"     , division = "III", label = "Bronze III"     , minScore = 1695, topPercent =  91.49 },
    { tier = "Bronze"     , division = "IV" , label = "Bronze IV"      , minScore = 1597, topPercent =  96.38 },
    { tier = "Iron"       , division = "I"  , label = "Iron I"         , minScore = 1561, topPercent =  98.18 },
    { tier = "Iron"       , division = "II" , label = "Iron II"        , minScore = 1542, topPercent =  99.13 },
    { tier = "Iron"       , division = "III", label = "Iron III"       , minScore = 1533, topPercent =  99.57 },
    { tier = "Iron"       , division = "IV" , label = "Iron IV"        , minScore = 1524, topPercent =    100 },
}

-- Tier colors as (r, g, b) in [0-1] range, matching the Tank-Me-Later web app.
TankMeLater.Data.TierColors = {
    Challenger  = { r = 0.957, g = 0.816, b = 0.247 },
    Grandmaster = { r = 0.910, g = 0.145, b = 0.231 },
    Master      = { r = 0.608, g = 0.349, b = 0.714 },
    Diamond     = { r = 0.310, g = 0.765, b = 0.969 },
    Emerald     = { r = 0.180, g = 0.800, b = 0.443 },
    Platinum    = { r = 0.102, g = 0.737, b = 0.612 },
    Gold        = { r = 0.953, g = 0.612, b = 0.071 },
    Silver      = { r = 0.584, g = 0.647, b = 0.651 },
    Bronze      = { r = 0.804, g = 0.498, b = 0.196 },
    Iron        = { r = 0.498, g = 0.549, b = 0.553 },
}
