-- AUTO-GENERATED by scripts/generate-rank-data.mjs — do not edit by hand.
-- Source: Tank-Me-Later Vercel API (falls back to Raider.io if unavailable).

TankMeLater = TankMeLater or {}
TankMeLater.Data = {}

-- Season metadata
TankMeLater.Data.Season      = "season-mn-1"
TankMeLater.Data.UpdatedDate = "2026-06-28"

-- Pre-computed minimum score for each rank boundary.
-- Ordered highest rank first (Challenger index 1, Iron IV last).
-- scoreToRank() scans this table and returns the first entry where score >= minScore.
TankMeLater.Data.Cutoffs = {
    { tier = "Challenger" , division = nil  , label = "Challenger"     , minScore = 4075, topPercent =   0.02 },
    { tier = "Grandmaster", division = nil  , label = "Grandmaster"    , minScore = 4059, topPercent =   0.08 },
    { tier = "Master"     , division = nil  , label = "Master"         , minScore = 3865, topPercent =   0.79 },
    { tier = "Diamond"    , division = "I"  , label = "Diamond I"      , minScore = 3789, topPercent =   1.37 },
    { tier = "Diamond"    , division = "II" , label = "Diamond II"     , minScore = 3741, topPercent =   2.31 },
    { tier = "Diamond"    , division = "III", label = "Diamond III"    , minScore = 3711, topPercent =   2.89 },
    { tier = "Diamond"    , division = "IV" , label = "Diamond IV"     , minScore = 3640, topPercent =   4.29 },
    { tier = "Emerald"    , division = "I"  , label = "Emerald I"      , minScore = 3520, topPercent =   6.63 },
    { tier = "Emerald"    , division = "II" , label = "Emerald II"     , minScore = 3430, topPercent =   8.39 },
    { tier = "Emerald"    , division = "III", label = "Emerald III"    , minScore = 3330, topPercent =  10.84 },
    { tier = "Emerald"    , division = "IV" , label = "Emerald IV"     , minScore = 3227, topPercent =  15.61 },
    { tier = "Platinum"   , division = "I"  , label = "Platinum I"     , minScore = 3176, topPercent =  17.96 },
    { tier = "Platinum"   , division = "II" , label = "Platinum II"    , minScore = 3101, topPercent =  21.46 },
    { tier = "Platinum"   , division = "III", label = "Platinum III"   , minScore = 3007, topPercent =  25.89 },
    { tier = "Platinum"   , division = "IV" , label = "Platinum IV"    , minScore = 2862, topPercent =  33.25 },
    { tier = "Gold"       , division = "I"  , label = "Gold I"         , minScore = 2786, topPercent =  37.09 },
    { tier = "Gold"       , division = "II" , label = "Gold II"        , minScore = 2677, topPercent =  42.58 },
    { tier = "Gold"       , division = "III", label = "Gold III"       , minScore = 2555, topPercent =  48.76 },
    { tier = "Gold"       , division = "IV" , label = "Gold IV"        , minScore = 2380, topPercent =  57.62 },
    { tier = "Silver"     , division = "I"  , label = "Silver I"       , minScore = 2292, topPercent =  62.05 },
    { tier = "Silver"     , division = "II" , label = "Silver II"      , minScore = 2181, topPercent =  67.66 },
    { tier = "Silver"     , division = "III", label = "Silver III"     , minScore = 2069, topPercent =  73.37 },
    { tier = "Silver"     , division = "IV" , label = "Silver IV"      , minScore = 1939, topPercent =  79.91 },
    { tier = "Bronze"     , division = "I"  , label = "Bronze I"       , minScore = 1863, topPercent =  83.76 },
    { tier = "Bronze"     , division = "II" , label = "Bronze II"      , minScore = 1780, topPercent =  87.96 },
    { tier = "Bronze"     , division = "III", label = "Bronze III"     , minScore = 1702, topPercent =  91.93 },
    { tier = "Bronze"     , division = "IV" , label = "Bronze IV"      , minScore = 1608, topPercent =   96.7 },
    { tier = "Iron"       , division = "I"  , label = "Iron I"         , minScore = 1573, topPercent =  98.46 },
    { tier = "Iron"       , division = "II" , label = "Iron II"        , minScore = 1557, topPercent =  99.28 },
    { tier = "Iron"       , division = "III", label = "Iron III"       , minScore = 1549, topPercent =  99.64 },
    { tier = "Iron"       , division = "IV" , label = "Iron IV"        , minScore = 1542, topPercent =    100 },
}

-- Tier colors as (r, g, b) in [0-1] range, matching the Tank-Me-Later web app.
TankMeLater.Data.TierColors = {
    Challenger  = { r = 0.957, g = 0.816, b = 0.247 },
    Grandmaster = { r = 0.910, g = 0.145, b = 0.231 },
    Master      = { r = 0.608, g = 0.349, b = 0.714 },
    Diamond     = { r = 0.310, g = 0.765, b = 0.969 },
    Emerald     = { r = 0.180, g = 0.800, b = 0.443 },
    Platinum    = { r = 0.102, g = 0.737, b = 0.612 },
    Gold        = { r = 0.953, g = 0.612, b = 0.071 },
    Silver      = { r = 0.584, g = 0.647, b = 0.651 },
    Bronze      = { r = 0.804, g = 0.498, b = 0.196 },
    Iron        = { r = 0.498, g = 0.549, b = 0.553 },
}
